site_name: Portafolio de Proyectos - David López Ramírez
site_description: Documentación de proyectos realizados por David López Ramírez.
nav:
  - Página principal: index.md
  - Formación académica:
      - Sistemas Embebidos I:
          #- Proyectos:
          - Tareas:
              - Tarea I - Comparación de microcontroladores: tarea_1.md
              - Tarea II - Outputs básicos: tarea_2.md
              - Tarea III - Inputs: tarea_3.md
              - Tarea IV - Mini-Pong: tarea_4.md
              - Tarea V - Comparación de alarmas: tarea_5.md
              - Tarea VI - Alarmas aplicadas: tarea_6.md
              - Tarea VII - Modulación por ancho de pulso - PWM: tarea_7.md
              - Tarea VIII - Comunicación UART: tarea_8.md
markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic:
      mode: view
  - pymdownx.caret
  - pymdownx.keys
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
theme:
  name: material
  highlightjs: true 
  palette:
    - scheme: default
      primary: red
  features:
    - content.code.copy
    - content.tooltips
extra_css:
  - https://use.fontawesome.com/releases/v6.5.2/css/all.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
